image: node:16
stages:
  - setup
  - test
  - build

install-dependencies:
  stage: setup
  interruptible: true
  only:
    - main
    - merge_requests
  cache:
    - key:
        files:
          - yarn.lock
      paths:
        - .yarn-cache/
  script:
    - yarn --frozen-lockfile --cache-folder .yarn-cache

.distributed:
  interruptible: true
  only:
    - main
    - merge_requests
  needs:
    - install-dependencies
  artifacts:
    paths:
      - node_modules/.cache/nx

workspace-lint:
  stage: test
  extends: .distributed
  script:
    - yarn nx workspace-lint

format-check:
  stage: test
  extends: .distributed
  script:
    - yarn nx format:check

lint:
  stage: test
  extends: .distributed
  script:
    - yarn nx affected --base=HEAD~1 --target=lint --parallel=3

test:
  stage: test
  extends: .distributed
  script:
    - yarn nx affected --base=HEAD~1 --target=test --parallel=3 --ci --code-coverage

build:
  stage: build
  extends: .distributed
  script:
    - yarn nx affected --base=HEAD~1 --target=build --parallel=3
