version: 2.1

# Variables
var_1: &working_directory ~/repo

machine:
  pre:
    - mkdir ~/.cache/yarn

dependencies:
  cache_directories:
    - ~/.cache/yarn

executors:
  default-executor:
    docker:
      - image: cimg/node:14.17-browsers
    working_directory: *working_directory

jobs:
  test:
    executor: default-executor
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
      SELECTED_PM: pnpm
      NX_E2E_CI_CACHE_KEY: e2e-circleci-linux-pnpm
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
      - run:
          name: Get Last Sucessful Tag
          shell: '/bin/bash'
          command: |
            source ./scripts/get-last-successful-tag.sh $CIRCLE_BRANCH main nx_successful_ci_run__* false
            echo "export AFFECTED_BASE=\"$BASE_SHA\";" >> $BASH_ENV
      - run:
          name: Install packages
          command: yarn install --prefer-offline --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Install PNPM
          command: npm install --prefix=$HOME/.local -g pnpm@6.7.6
      - run:
          name: Run Lint
          shell: '/bin/bash'
          command: |
            echo $CIRCLE_WORKFLOW_ID
            echo $CIRCLE_BRANCH
            npx nx affected --target=lint --base=$AFFECTED_BASE
            npx nx affected --target=lint --base={{ AFFECTED_BASE }}
            npx nx affected --target=lint --base=$(echo $AFFECTED_BASE )
      - run:
          name: Run Test
          command: |
            echo $CIRCLE_WORKFLOW_ID
            echo $CIRCLE_BRANCH
            npx nx affected --target=test --base=$AFFECTED_BASE
            npx nx affected --target=test --base={{ AFFECTED_BASE }}
            npx nx affected --target=test --base=$(echo $AFFECTED_BASE )

      - run:
          when: on_success
          shell: '/bin/bash'
          name: Save successful tag
          command: |
            ./scripts/tag-successful-build.sh nx_successful_ci_run__${CIRCLE_WORKFLOW_ID}__$(date +"%Y-%m-%d-%H%M")-UTC

workflows:
  testing:
    jobs:
      - test
