version: 2.1

# -------------------------
#        DEFAULTS
# -------------------------
machine:
  pre:
    - mkdir ~/.cache/yarn

dependencies:
  cache_directories:
    - ~/.cache/yarn

defaults: &defaults
  working_directory: ~/repo

# -------------------------
#        EXECUTORS
# -------------------------

orbs:
  nx: nrwl/nx@dev:alpha
  android: circleci/android@1.0.3

executors:
  linux:
    <<: *defaults
    docker:
      - image: cimg/node:14.17-browsers

jobs:
  test:
    parameters:
      workflow_id:
        type: string
        default: 'none'
    executor: linux
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
      SELECTED_PM: pnpm
      NX_E2E_CI_CACHE_KEY: e2e-circleci-linux-pnpm
      MY_MIX: my-mix-<< parameters.workflow_id >>
    steps:
      - checkout
      # - restore_cache:
      #     name: Restore Yarn Package Cache
      #     # See the configuration reference documentation for more details on using restore_cache and save_cache steps
      #     # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
      #     keys:
      #       - yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
      - run:
          name: test env
          command: |
            echo "$CIRCLE_BUILD_URL"
      - nx/set-shas:
          allow-on-hold-workflow: true
      # - run:
      #     name: Set base and head SHAs used for nx affected
      #     command: |
      #       RESPONSE=$(node scripts/circleci/find-successful-workflow.js $CIRCLE_BUILD_URL $CIRCLE_BRANCH main false)
      #       echo "$RESPONSE"
      #       BASE_SHA=$(echo "$RESPONSE" | grep 'Commit:' | sed 's/.*Commit: //')
      #       HEAD_SHA=$(git rev-parse HEAD)
      #       echo "export NX_BASE=\"$BASE_SHA\";" >> $BASH_ENV
      #       echo "export NX_HEAD=\"$HEAD_SHA\";" >> $BASH_ENV

      # - run:
      #     name: Log base and head SHAs used for nx affected
      #     command: |
      #       echo "Base SHA"
      #       echo $NX_BASE
      #       echo ""
      #       echo "Head SHA"
      #       echo $NX_HEAD
      #       echo ""
      # - run:
      #     name: Install packages
      #     command: yarn install --prefer-offline --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      # - save_cache:
      #     key: yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      # - run:
      #     name: Install PNPM
      #     command: npm install --prefix=$HOME/.local -g pnpm@6.7.6
      # - run:
      #     name: Run Lint
      #     command: |
      #       echo "BASE: $NX_BASE"
      #       echo "HEAD: $NX_HEAD"
      #       echo "MIX: $YOUR_MIX"

workflows:
  testing:
    jobs:
      - test
      #     workflow_id: $CIRCLE_WORKFLOW_ID
