version: 2.1

# Variables
var_1: &working_directory ~/repo

machine:
  pre:
    - mkdir ~/.cache/yarn

dependencies:
  cache_directories:
    - ~/.cache/yarn

executors:
  default-executor:
    docker:
      - image: cimg/node:14.17-browsers
    working_directory: *working_directory

jobs:
  test:
    executor: default-executor
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
      SELECTED_PM: pnpm
      NX_E2E_CI_CACHE_KEY: e2e-circleci-linux-pnpm
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          # See the configuration reference documentation for more details on using restore_cache and save_cache steps
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
          keys:
            - yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
      - run:
          name: Get Last Sucessful Run
          command: |
            source ./scripts/circleci/get-successful-run.sh << pipeline.project.type >>/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME $CIRCLE_BRANCH main false
            echo "export NX_BASE=\"$BASE_SHA\";" >> $BASH_ENV
            echo "export NX_HEAD=\"$HEAD_SHA\";" >> $BASH_ENV
      - run:
          name: Install packages
          command: yarn install --prefer-offline --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          key: yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Install PNPM
          command: npm install --prefix=$HOME/.local -g pnpm@6.7.6
      - run:
          name: Run Lint
          command: |
            npx nx affected --target=lint --base=$NX_BASE
      - run:
          name: Run Test
          command: |
            npx nx affected --target=test --base=$NX_BASE

workflows:
  testing:
    jobs:
      - test
