version: 2.1

# -------------------------
#        DEFAULTS
# -------------------------
machine:
  pre:
    - mkdir ~/.cache/yarn

dependencies:
  cache_directories:
    - ~/.cache/yarn

defaults: &defaults
  working_directory: ~/repo

# -------------------------
#        EXECUTORS
# -------------------------

orbs:
  nx: nrwl/nx@1.0.0
  android: circleci/android@1.0.3

executors:
  linux:
    <<: *defaults
    docker:
      - image: cimg/node:14.17-browsers

  macos:
    <<: *defaults
    macos:
      xcode: &_XCODE_VERSION '12.5.0'

  rmandroid:
    <<: *defaults
    docker:
      - image: reactnativecommunity/react-native-android
    resource_class: large
    environment:
      - ADB_INSTALL_TIMEOUT: 10
      - _JAVA_OPTIONS: '-Xmx1024m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      - GRADLE_OPTS: '-Xmx2014m -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-XX:+UnlockExperimentalVMOptions -XX:+HeapDumpOnOutOfMemoryError"'

jobs:
  android-test:
    executor: rmandroid
    steps:
      - run:
          name: Check process
          command: |
            echo "console.log(process.platform === 'linux' && process.env.ANDROID_HOME && process.env.ANDROID_SDK_ROOT);console.log('In for a treat')" >> "index.js"
            echo "$(node index.js)"
        # RESPONSE=$(node index.js)
        # echo "$RESPONSE"
  android-test2:
    executor:
      name: android/android-machine
      resource-class: large
    steps:
      - run:
          name: Check process
          command: |
            echo "console.log(process.platform === 'linux' && process.env.ANDROID_HOME && process.env.ANDROID_SDK_ROOT);console.log('In for a treat')" >> "index.js"
            echo "$(node index.js)"
  ubuntu-test:
    executor: linux
    steps:
      - run:
          name: Check process
          command: |
            echo "console.log(process.platform === 'linux' && process.env.ANDROID_HOME && process.env.ANDROID_SDK_ROOT);console.log('In for a treat')" >> "index.js"
            echo "$(node index.js)"
  macos-test:
    executor: macos
    steps:
      - run:
          name: Check process
          command: |
            echo "console.log(process.platform === 'linux' && process.env.ANDROID_HOME && process.env.ANDROID_SDK_ROOT);console.log('In for a treat')" >> "index.js"
            echo "$(node index.js)"

  test:
    parameters:
      workflow_id:
        type: string
        default: 'none'
    executor: linux
    environment:
      NX_CLOUD_DISTRIBUTED_EXECUTION: 'false'
      SELECTED_PM: pnpm
      NX_E2E_CI_CACHE_KEY: e2e-circleci-linux-pnpm
      MY_MIX: my-mix-<< parameters.workflow_id >>
    steps:
      - checkout
      - run:
          name: Check the value
          command: |
            echo "export YOUR_MIX=\"your-mix-<< parameters.workflow_id>>\";" >> $BASH_ENV
            echo << parameters.workflow_id>>
            echo $MY_MIX
            echo $YOUR_MIX
      # - restore_cache:
      #     name: Restore Yarn Package Cache
      #     # See the configuration reference documentation for more details on using restore_cache and save_cache steps
      #     # https://circleci.com/docs/2.0/configuration-reference/?section=reference#save_cache
      #     keys:
      #       - yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
      # - nx/set-shas
      # - run:
      #     name: Set base and head SHAs used for nx affected
      #     command: |
      #       RESPONSE=$(node scripts/circleci/find-successful-workflow.js $CIRCLE_BUILD_URL $CIRCLE_BRANCH main false)
      #       echo "$RESPONSE"
      #       BASE_SHA=$(echo "$RESPONSE" | grep 'Commit:' | sed 's/.*Commit: //')
      #       HEAD_SHA=$(git rev-parse HEAD)
      #       echo "export NX_BASE=\"$BASE_SHA\";" >> $BASH_ENV
      #       echo "export NX_HEAD=\"$HEAD_SHA\";" >> $BASH_ENV

      # - run:
      #     name: Log base and head SHAs used for nx affected
      #     command: |
      #       echo "Base SHA"
      #       echo $NX_BASE
      #       echo ""
      #       echo "Head SHA"
      #       echo $NX_HEAD
      #       echo ""
      # - run:
      #     name: Install packages
      #     command: yarn install --prefer-offline --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      # - save_cache:
      #     key: yarn-packages-{{ .Branch }}>-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      # - run:
      #     name: Install PNPM
      #     command: npm install --prefix=$HOME/.local -g pnpm@6.7.6
      - run:
          name: Run Lint
          command: |
            echo "BASE: $NX_BASE"
            echo "HEAD: $NX_HEAD"
            echo "MIX: $YOUR_MIX"

workflows:
  testing:
    jobs:
      # - test:
      #     workflow_id: $CIRCLE_WORKFLOW_ID
      - android-test
      - android-test2
      - ubuntu-test
      - macos-test
