#!/bin/bash

GITHUB_TOKEN=$1
GITHUB_EVENT_NAME=$2
INPUTS_MAIN_BRANCH_NAME=$3
INPUTS_ERROR_ON_NO_SUCCESSFUL_WORKFLOW=$4

echo "THIS IS WHAT I GOT: $GITHUB_TOKEN $GITHUB_EVENT_NAME $INPUTS_MAIN_BRANCH_NAME $INPUTS_ERROR_ON_NO_SUCCESSFUL_WORKFLOW"

RESULT=$(node .github/actions/nx-set-shas/find-successful-workflow.js $GITHUB_TOKEN $INPUTS_MAIN_BRANCH_NAME)

echo "RES $RESULT"
