#!/bin/bash

GITHUB_WORKFLOW_ID=$1
GITHUB_EVENT_NAME=$2
INPUTS_MAIN_BRANCH_NAME=$3
INPUTS_ERROR_ON_NO_SUCCESSFUL_WORKFLOW=$4

SHA=$(node .github/actions/nx-set-shas/find-successful-workflow.js $GITHUB_WORKFLOW_ID $INPUTS_MAIN_BRANCH_NAME)

echo "RES $SHA"
