name: Project lint (with published action)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install packages
        run: yarn install --prefer-offline --non-interactive

      - name: Set base and head SHAs used for nx affected
        uses: ./.github/actions/nx-set-shas
        id: setSHAs

      - name: Run Lint
        run: yarn nx affected --target=lint --base=${{ steps.setSHAs.outputs.base }}
      - name: Run Test
        run: yarn nx affected --target=test --base=${{ steps.setSHAs.outputs.base }}
