name: Project check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: Cache yarn
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-
      - name: Install packages
        run: yarn install --prefer-offline --non-interactive

      - name: Set base and head SHAs used for nx affected (inner)
        uses: ./.github/actions/nx-set-shas
        id: last_successful_commit
        with:
          workflow-id: 'ci.yml'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set base and head SHAs used for nx affected (outer)
        id: setSHAs
        shell: bash
        run: ./scripts/circleci/get-successful-github-run.sh ${{ secrets.GITHUB_TOKEN }} ${{ github.event_name }} main false

      # - name: Run Lint
      #   run: yarn nx affected --target=lint
      # - name: Run Test
      #   run: yarn nx affected --target=test
